version: '3.3'

services:
  airflow:
    build: ./airflow
    restart: unless-stopped
    ports:
      - "9000:8000"
  provider-a:
    build: ./provider-a
    restart: unless-stopped
    ports:
      - "5000:8000"
  provider-b:
    build: ./provider-b
    restart: unless-stopped
    ports:
      - "5001:8000"

