version: '3.3'

services:
  airflow:
    build: ./airflow
    restart: unless-stopped
    network_mode: host
  provider-a:
    build: ./provider-a
    restart: unless-stopped
    ports:
      - "8000:8000"
  provider-b:
    build: ./provider-b
    restart: unless-stopped
    ports:
      - "8001:8001"
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "10000:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
